[url]
url="https://www.polyphia.com/products/remember-that-you-will-die-genesis-variant-lp"

[settings]
webhooks=false

[discord]
webhook="https://discord.com/api/webhooks/1025677279256391700/5zngIDcXLqIP6F93COqphkQD3F7wUjuo1c5ZtVjltpusQ4YW01Gmeyud5B2OrQBkLRVt" 
my_id=249547320306171907