url = [
    "https://www.polyphia.com/products/remember-that-you-will-die-genesis-variant-lp",
    "https://www.polyphia.com/products/remember-that-you-will-die-ego-death-variant-lp",
    "https://www.polyphia.com/products/remember-that-you-will-die-memento-mori-variant-lp",
    "https://www.polyphia.com/products/polyheadbl-ts?variant=32398211612771"
]

[settings]
cooldown=25
webhooks=false

[discord]
webhook="https://discord.com/api/webhooks/example" 
my_id=123456789
